import Head from 'next/head'

import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'


export default function Home() {
 return (
    <div>
        <Head>
            <title>Rohit | Web Developer</title>
            <meta name='description' content='generated by me'   />
            <link />
        </Head>
       
        <Main/>
        <About/>
        <Skills/>
        <Projects/>
        <Contact/>
    </div>
 )
 
}
